---
version: "2"
plugins:
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
  radon:
    enabled: true
  scss-lint:
    enabled: false
exclude_patterns:
  - "*.test.js"
  - "game/_version.py"
  - "versioneer.py"
  - "game_frontend/djangoBundler.js"
