coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch:
      default:
        target: 90%

ignore:
  - "aimmo_setup.py"
  - "run.py"
  - "aimmo/static/*"
  - "aimmo/static/**/*"
  - "aimmo/static/**/**/*"
  - "aimmo-game/agones/*"
  - "aimmo-game/agones/**/*"
  - "aimmo_runner/*"
  - "aimmo_runner/**/*"
  - "test_utils/*"
  - "setup.py"

comment:
  layout: "reach, diff, flags, files"
  behavior: new
  require_changes: false
  require_base: no
  require_head: yes
  branches:
    - "!master"
