---
version: '2'
plugins:
  csslint:
    enabled: true
  eslint:
    enabled: true
    config:
      config: game_frontend/.eslintrc.json
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
  radon:
    enabled: true
  scss-lint:
    enabled: false
exclude_patterns:
  - '**/node_modules/'
  - '**/*.test.js'
  - '*/tests/**/*.py'
  - 'game/_version.py'
  - 'versioneer.py'
  - 'game_frontend/djangoBundler.js'
  - 'game_frontend/dist/'
  - 'aimmo/avatar_examples/**'
  - 'aimmo/static/pyodide/**'
  - 'aimmo/static/react/'
  - 'aimmo-game/agones/**'
  - 'example_project/example_project/static'
  - 'build/'
