apiVersion: v1
kind: ServiceAccount
metadata:
  name: game-creator

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: game-creator
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["replicationcontrollers", "pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["ingresses"]
  verbs: ["patch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-games
  namespace: default
subjects:
- kind: ServiceAccount
  name: game-creator # Name is case sensitive
  apiGroup: ""
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: game-creator # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""