#!/bin/bash
set -e
cd "${BASH_SOURCE%/*}"

trap 'kill -- -$$' INT TERM

pip install -e .
./example_project/manage.py migrate --noinput
./example_project/manage.py collectstatic --noinput
./aimmo-game/service.py &
./example_project/manage.py runserver "$@" &
wait
