# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-07-23 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimmo', '0016_game_game_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_class',
        ),
    ]
