# Generated by Django 2.2.24 on 2021-11-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimmo', '0025_generate_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='worksheet',
        ),
        migrations.AddField(
            model_name='game',
            name='worksheet_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='auth_token',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.DeleteModel(
            name='Worksheet',
        ),
    ]
