# Generated by Django 3.2.20 on 2023-07-26 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aimmo', '0032_alter_game_target_num_pickups_per_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='can_play',
            field=models.ManyToManyField(blank=True, help_text='List of auth_user IDs of users who are allowed to play and have access to the game.', null=True, related_name='playable_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
