# Generated by Django 3.2.20 on 2023-08-02 16:21

import aimmo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimmo', '0033_alter_game_can_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='auth_token',
            field=models.CharField(blank=True, default=aimmo.models.generate_avatar_auth_token, max_length=24),
        ),
        migrations.AlterField(
            model_name='game',
            name='auth_token',
            field=models.CharField(blank=True, default=aimmo.models.generate_game_auth_token, max_length=48),
        ),
    ]
