# Generated by Django 3.2.23 on 2023-11-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimmo', '0036_worksheetbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheetusage',
            name='loaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
