const SOCKET_CONSOLE_LOG_RECEIVED = 'features/ConsoleLog/SOCKET_CONSOLE_LOG_RECEIVED'
const CLEAR_CONSOLE_LOGS = 'features/ConsoleLog/CLEAR_CONSOLE_LOGS'

export default {
  SOCKET_CONSOLE_LOG_RECEIVED,
  CLEAR_CONSOLE_LOGS,
}
