const SOCKET_CONSOLE_LOG_RECEIVED = 'features/ConsoleLog/SOCKET_CONSOLE_LOG_RECEIVED'
const CLEAR_CONSOLE_LOGS = 'features/ConsoleLog/CLEAR_CONSOLE_LOGS'
const APPEND_PAUSE_MESSAGE = 'features/ConsoleLog/APPEND_PAUSE_MESSAGE'

export default {
  SOCKET_CONSOLE_LOG_RECEIVED,
  CLEAR_CONSOLE_LOGS,
  APPEND_PAUSE_MESSAGE,
}
