const INITIALIZE_PYODIDE = 'features/AvatarWorker/INITIALIZE_PYODIDE'
const PYODIDE_INITIALIZED = 'features/AvatarWorker/PYODIDE_INITIALIZED'

const AVATAR_CODE_UPDATED = 'features/AvatarWorker/AVATAR_CODE_UPDATED'

const AVATARS_NEXT_ACTION_COMPUTED = 'features/AvatarWorker/AVATARS_NEXT_ACTION_COMPUTED'

export default {
  AVATAR_CODE_UPDATED,
  PYODIDE_INITIALIZED,
  AVATARS_NEXT_ACTION_COMPUTED,
  INITIALIZE_PYODIDE
}
