const INITIALIZE_PYODIDE = 'features/AvatarWorker/INITIALIZE_PYODIDE'
const PYODIDE_INITIALIZED = 'features/AvatarWorker/PYODIDE_INITIALIZED'

const AVATAR_CODE_UPDATED = 'features/AvatarWorker/AVATAR_CODE_UPDATED'

const AVATARS_NEXT_ACTION_COMPUTED = 'features/AvatarWorker/AVATARS_NEXT_ACTION_COMPUTED'

const BADGES_CHECKED = 'features/AvatarWorker/BADGES_CHECKED'
const BADGES_CHECKED_FAILURE = 'features/AvatarWorker/BADGES_CHECKED_FAILURE'
const GET_BADGES_REQUEST = 'features/AvatarWorker/GET_CODE_REQUEST'
const GET_BADGES_SUCCESS = 'features/AvatarWorker/GET_CODE_SUCCESS'
const GET_BADGES_FAILURE = 'features/AvatarWorker/GET_CODE_FAILURE'
const POST_BADGES_REQUEST = 'features/AvatarWorker/POST_CODE_REQUEST'
const POST_BADGES_SUCCESS = 'features/AvatarWorker/POST_CODE_SUCCESS'
const POST_BADGES_FAILURE = 'features/AvatarWorker/POST_CODE_FAILURE'

export default {
  AVATAR_CODE_UPDATED,
  PYODIDE_INITIALIZED,
  AVATARS_NEXT_ACTION_COMPUTED,
  INITIALIZE_PYODIDE,
  BADGES_CHECKED,
  BADGES_CHECKED_FAILURE,
  GET_BADGES_REQUEST,
  GET_BADGES_SUCCESS,
  GET_BADGES_FAILURE,
  POST_BADGES_REQUEST,
  POST_BADGES_SUCCESS,
  POST_BADGES_FAILURE,
}
