# coding: utf-8

"""
    sdk.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GameServerStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'state': 'str',
        'address': 'str',
        'ports': 'list[StatusPort]',
        'players': 'StatusPlayerStatus'
    }

    attribute_map = {
        'state': 'state',
        'address': 'address',
        'ports': 'ports',
        'players': 'players'
    }

    def __init__(self, state=None, address=None, ports=None, players=None):  # noqa: E501
        """GameServerStatus - a model defined in Swagger"""  # noqa: E501
        self._state = None
        self._address = None
        self._ports = None
        self._players = None
        self.discriminator = None
        if state is not None:
            self.state = state
        if address is not None:
            self.address = address
        if ports is not None:
            self.ports = ports
        if players is not None:
            self.players = players

    @property
    def state(self):
        """Gets the state of this GameServerStatus.  # noqa: E501


        :return: The state of this GameServerStatus.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this GameServerStatus.


        :param state: The state of this GameServerStatus.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def address(self):
        """Gets the address of this GameServerStatus.  # noqa: E501


        :return: The address of this GameServerStatus.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this GameServerStatus.


        :param address: The address of this GameServerStatus.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def ports(self):
        """Gets the ports of this GameServerStatus.  # noqa: E501


        :return: The ports of this GameServerStatus.  # noqa: E501
        :rtype: list[StatusPort]
        """
        return self._ports

    @ports.setter
    def ports(self, ports):
        """Sets the ports of this GameServerStatus.


        :param ports: The ports of this GameServerStatus.  # noqa: E501
        :type: list[StatusPort]
        """

        self._ports = ports

    @property
    def players(self):
        """Gets the players of this GameServerStatus.  # noqa: E501


        :return: The players of this GameServerStatus.  # noqa: E501
        :rtype: StatusPlayerStatus
        """
        return self._players

    @players.setter
    def players(self, players):
        """Sets the players of this GameServerStatus.


        :param players: The players of this GameServerStatus.  # noqa: E501
        :type: StatusPlayerStatus
        """

        self._players = players

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GameServerStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GameServerStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
