AVATAR_STARTING_HEALTH = 5
SCORE_PENALTY_ON_DEATH = 10
DEFAULT_ATTACK_DAMAGE = 1

TARGET_NUM_CELLS_PER_AVATAR = 16

TARGET_NUM_SCORE_LOCATIONS_PER_AVATAR = 0.5
SCORE_DESPAWN_CHANCE = 0.02

TARGET_NUM_PICKUPS_PER_AVATAR = 0.5
PICKUP_SPAWN_CHANCE = 0.02

NO_FOG_OF_WAR_DISTANCE = 2
PARTIAL_FOG_OF_WAR_DISTANCE = 3