apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-registry
  labels:
    k8s-app: kube-registry
spec:
  selector:
    k8s-app: kube-registry
  ports:
  - name: registry
    port: 5000
    protocol: TCP
