apiVersion: 'agones.dev/v1'
kind: Fleet
metadata:
  name: aimmo-game
spec:
  replicas: 15
  strategy:
    type: Recreate
  template:
    spec:
      ports:
        - name: default
          protocol: TCPUDP
          containerPort: 5000
      health:
        initialDelaySeconds: 30
      template:
        spec:
          serviceAccountName: worker-manager
          containers:
            - name: aimmo-game
              image: ocadotechnology/aimmo-game:test
              env:
                - name: GAME_API_URL
                  value: https://localhost:8000/api/
                - name: GAME_MANAGER
                  value: kubernetes
              resources:
                requests:
                  memory: '64Mi'
                  cpu: '24m'
                limits:
                  memory: '124Mi'
                  cpu: '95m'
