apiVersion: v1
kind: ReplicationController
metadata:
  name: aimmo-game-creator
spec:
  replicas: 1
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: aimmo-game-creator
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: aimmo-game-creator
    spec:
      containers:
      - name: aimmo-game-creator
        image: ocadotechnology/aimmo-game-creator:latest
        ports:
        - containerPort: 80
        env:
        - name: IMAGE_SUFFIX
          value: latest
        - name: GAME_API_URL
          value: https://staging-dot-decent-digit-629.appspot.com/aimmo/api/games/
        - name: WORKER_MANAGER
          value: kubernetes
