const GET_CODE_REQUEST = 'features/Editor/GET_CODE_REQUEST'
const GET_CODE_SUCCESS = 'features/Editor/GET_CODE_SUCCESS'
const GET_CODE_FAILURE = 'features/Editor/GET_CODE_FAILURE'

const POST_CODE_REQUEST = 'features/Editor/POST_CODE_REQUEST'
const POST_CODE_SUCCESS = 'features/Editor/POST_CODE_SUCCESS'
const POST_CODE_FAILURE = 'features/Editor/POST_CODE_FAILURE'
const RESET_CODE = 'features/Editor/RESET_CODE'
const CODE_RESET = 'features/Editor/CODE_RESET'

export default {
  GET_CODE_REQUEST,
  GET_CODE_SUCCESS,
  GET_CODE_FAILURE,
  POST_CODE_REQUEST,
  POST_CODE_SUCCESS,
  POST_CODE_FAILURE,
  RESET_CODE,
  CODE_RESET
}
