const SEND_ANALYTICS_EVENT = 'features/Analytics/SEND_ANALYTICS_EVENT'
const ANALYTICS_EVENT_SENT = 'features/Analytics/ANALYTICS_EVENT_SENT'
const SEND_ANALYTICS_TIMING_EVENT = 'features/Analytics/SEND_ANALYTICS_TIMING_EVENT'
const ANALYTICS_TIMING_EVENT_SENT = 'features/Analytics/ANALYTICS_TIMING_EVENT_SENT'
export default {
  SEND_ANALYTICS_EVENT,
  ANALYTICS_EVENT_SENT,
  SEND_ANALYTICS_TIMING_EVENT,
  ANALYTICS_TIMING_EVENT_SENT,
}
