name: CI
on: push  # TODO: change to PR
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7.x
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev --system
        cd game_frontend
        yarn install
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        install: false
        start: python ../run.py -c
        working-directory: game_frontend
        wait-on: http://localhost:8000
        wait-on-timeout: 400
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
