name: Publish Python Package
on:
  push:
  workflow_run:
    workflows: ['CI']
    branches: [master]
    types:
      - completed
jobs:
  publish:
    name: Publish aimmo PyPi package
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}  # TODO: uncomment after testing
    runs-on: ubuntu-18.04
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.x
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install frontend dependencies
        run: |
          cd game_frontend
          yarn --frozen-lockfile
      - name: Install wheel
        run: pip install wheel
      - name: Build worker wheel
        run: ./aimmo_runner/build_worker_wheel.sh
      - name: Bundle Frontend
        run: |
          cd game_frontend
          node djangoBundler.js
      - name: Semantic Release
        run: |
          pip install git+https://github.com/ocadotechnology/python-semantic-release.git@add_beta_releases
          semantic-release publish --branch=${GITHUB_REF##*/} --build=${{ github.run_number }}
      - name: Notify Semaphore (Staging)
        run: curl -d POST -v https://semaphoreci.com/api/v1/projects/${SEMAPHORE_PROJECT_ID}/master/build?auth_token=${SEMAPHORE_API_AUTH}
        env:
          SEMAPHORE_PROJECT_ID: ${{ secrets.SEMAPHORE_PROJECT_ID }}
          SEMAPHORE_API_AUTH: ${{ secrets.SEMAPHORE_API_AUTH }}
