name: Publish Python Package
on:
  push:
    branches:
      - master
    paths-ignore:
      - "CHANGELOG.md"
      - "aimmo/__init__.py"
jobs:
  publish-pypi-package:
    name: Publish PyPi Package
    runs-on: ubuntu-18.04
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: "x64"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install frontend dependencies
        run: |
          cd game_frontend
          yarn --frozen-lockfile
      - name: Install wheel
        run: pip install wheel
      - name: Build worker wheel
        run: ./aimmo_runner/build_worker_wheel.sh
      - name: Bundle Frontend
        run: |
          cd game_frontend
          node djangoBundler.js
      - name: Release aimmo
        uses: relekang/python-semantic-release@v7.25.2
        with:
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
