name: Snyk
on:
  release:
    types: [published]
  pull_request:
jobs:
  security:
    name: Run Snyk
    runs-on: ubuntu-20.04
    env:
      LANG: C.UTF-8
    steps:
      - name: Print git commit data
        run: |
          echo "Get commit info"
          echo " - ${{ env.GIT_COMMIT_SHA }}"
          echo " - ${{ env.GIT_COMMIT_SHORT_SHA }}"
          echo "Get author info"
          echo " - ${{ env.GIT_COMMIT_AUTHOR }}"
          echo " - ${{ env.GIT_COMMIT_AUTHOR_NAME }}"
          echo " - ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
          echo "Get committer info"
          echo " - ${{ env.GIT_COMMIT_COMMITTER }}"
          echo " - ${{ env.GIT_COMMIT_COMMITTER_NAME }}"
          echo " - ${{ env.GIT_COMMIT_COMMITTER_EMAIL }}"
          echo "Get message info"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT_SANITIZED }}"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_BODY }}"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Node dependencies
        run: |
          cd game_frontend
          yarn --frozen-lockfile
      - name: Run Snyk to check for vulnerabilities in Node.js
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor --file=game_frontend/package.json --package-manager=npm --project-name="aimmo_frontend"
      - name: Setup python-version
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          architecture: "x64"
      - name: Install Python dependencies
        run: |
          pip install pipenv
          pipenv install --dev --system
      - name: Generate requirements
        run: pip freeze --all > requirements.txt
      - name: Run Snyk to check for vulnerabilities in Python
        uses: snyk/actions/python-3.7@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor --file=requirements.txt --package-manager=pip --project-name="aimmo"
