name: Python style check
on:
  push:
    branches:
      - github_actions-1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Python style check
      uses: bulv1ne/python-style-check@v0.3
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
