const SOCKET_CONNECT_TO_GAME_REQUEST = 'features/Game/SOCKET_CONNECT_TO_GAME_REQUEST'
const SOCKET_CONNECT_TO_GAME_FAIL = 'features/Game/SOCKET_CONNECT_TO_GAME_FAIL'

const SOCKET_GAME_STATE_RECEIVED = 'features/Game/SOCKET_GAME_STATE_RECEIVED'
const SEND_GAME_STATE_SUCCESS = 'features/Game/SOCKET_GAME_STATE_UPDATE_SUCCESS'
const SEND_GAME_STATE_FAIL = 'features/Game/SOCKET_GAME_STATE_UPDATE_FAIL'

const UNITY_EVENT = 'features/Game/UNITY_EVENT' // check naming

const CONNECTION_PARAMETERS_RECEIVED = 'features/GAME/CONNECTION_PARAMETERS_RECEIVED'

const UNITY_SEND_AVATAR_ID_SUCCESS = 'features/GAME/UNITY_SEND_AVATAR_ID_SUCCESS'
const UNITY_SEND_AVATAR_ID_FAIL = 'features/GAME/UNITY_SEND_AVATAR_ID_FAIL'

export default {
  SOCKET_CONNECT_TO_GAME_REQUEST,
  SOCKET_CONNECT_TO_GAME_FAIL,
  SOCKET_GAME_STATE_RECEIVED,
  SEND_GAME_STATE_SUCCESS,
  SEND_GAME_STATE_FAIL,
  UNITY_EVENT,
  CONNECTION_PARAMETERS_RECEIVED,
  UNITY_SEND_AVATAR_ID_SUCCESS,
  UNITY_SEND_AVATAR_ID_FAIL
}
