const SOCKET_CONNECT_TO_GAME_REQUEST = 'features/Game/SOCKET_CONNECT_TO_GAME_REQUEST'
const SOCKET_CONNECT_TO_GAME_FAIL = 'features/Game/SOCKET_CONNECT_TO_GAME_FAIL'

const SOCKET_GAME_STATE_RECEIVED = 'features/Game/SOCKET_GAME_STATE_RECEIVED'
const SEND_GAME_STATE_SUCCESS = 'features/Game/SOCKET_GAME_STATE_UPDATE_SUCCESS'
const SEND_GAME_STATE_FAIL = 'features/Game/SOCKET_GAME_STATE_UPDATE_FAIL'

const UNITY_EVENT = 'features/Game/UNITY_EVENT'

const CONNECTION_PARAMETERS_RECEIVED = 'features/Game/CONNECTION_PARAMETERS_RECEIVED'

const UNITY_SEND_AVATAR_ID_SUCCESS = 'features/Game/UNITY_SEND_AVATAR_ID_SUCCESS'
const UNITY_SEND_AVATAR_ID_FAIL = 'features/Game/UNITY_SEND_AVATAR_ID_FAIL'

const SOCKET_FEEDBACK_AVATAR_UPDATED_SUCCESS = 'features/Game/SOCKET_FEEDBACK_AVATAR_UPDATED_SUCCESS'
const SOCKET_FEEDBACK_AVATAR_UPDATED_TIMEOUT = 'features/Game/SOCKET_FEEDBACK_AVATAR_UPDATED_TIMEOUT'
const SNACKBAR_FOR_AVATAR_FEEDBACK_SHOWN = 'features/Game/SNACKBAR_FOR_AVATAR_FEEDBACK_SHOWN'

const GAME_DATA_LOADED = 'features/Game/GAME_DATA_LOADED'

export default {
  SOCKET_CONNECT_TO_GAME_REQUEST,
  SOCKET_CONNECT_TO_GAME_FAIL,
  SOCKET_GAME_STATE_RECEIVED,
  SEND_GAME_STATE_SUCCESS,
  SEND_GAME_STATE_FAIL,
  UNITY_EVENT,
  CONNECTION_PARAMETERS_RECEIVED,
  UNITY_SEND_AVATAR_ID_SUCCESS,
  UNITY_SEND_AVATAR_ID_FAIL,
  SOCKET_FEEDBACK_AVATAR_UPDATED_SUCCESS,
  SOCKET_FEEDBACK_AVATAR_UPDATED_TIMEOUT,
  SNACKBAR_FOR_AVATAR_FEEDBACK_SHOWN,
  GAME_DATA_LOADED
}
