const GET_CONNECTION_PARAMETERS_REQUEST = 'features/Game/GET_CONNECTION_PARAMETERS_REQUEST'
const GET_CONNECTION_PARAMETERS_SUCCESS = 'features/Game/GET_CONNECTION_PARAMETERS_SUCCESS'
const GET_CONNECTION_PARAMETERS_FAIL = 'features/Game/GET_CONNECTION_PARAMETERS_FAIL'

const GAME_STATE_EVENT_RECEIVED = 'features/Game/SOCKET_GAME_STATE_RECEIVED'
const SEND_GAME_UPDATE_SUCCESS = 'features/Game/SOCKET_GAME_STATE_UPDATE_SUCCESS'
const SEND_GAME_UPDATE_FAIL = 'features/Game/SOCKET_GAME_STATE_UPDATE_FAIL'

const UNITY_EVENT = 'features/Game/UNITY_EVENT' // check naming

export default {
  GET_CONNECTION_PARAMETERS_REQUEST,
  GET_CONNECTION_PARAMETERS_SUCCESS,
  GET_CONNECTION_PARAMETERS_FAIL,
  GAME_STATE_EVENT_RECEIVED,
  SEND_GAME_UPDATE_SUCCESS,
  SEND_GAME_UPDATE_FAIL,
  UNITY_EVENT,
}
